# Pagination settings
paginate: 10  # Number of posts per page
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  

#-------------------------------
# General Site Settings
title: Bini Teklehaimanot
description: "Principal Data Science Consultant specializing in investment strategy, predictive modeling, and causal inference. My portfolio highlights applied machine learning projects with measurable ROI impact."
baseurl: "" 
url: "https://btexpress1.github.io"

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Kirkland, WA, USA"
resume_url: /docs/BiniTeklehaimanot_Resume.docx
avatar_image: /img/Bini.JPG

#-------------------------------
# Contact links
linkedin: "https://www.linkedin.com/in/binilt"
github: "https://github.com/btexpress1"
email: "bini@amajeybeacon.com"

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false

#-------------------------------
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
